(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: iPhysics_2.4.master                                          *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.12436.master                                             *)
(*        Build: e734d0bb0                                                    *)
(*         Date: 2021-11-11, Time: 12:10:57                                   *)
(*                                                                            *)

TYPE
ComTCP20_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 6;

        Kolben_CurveLength : REAL := 0.0;
        (* REAL Kolben_CurveLength *)
        Kolben_AXIS : REAL := 0.0;
        (* REAL Kolben_AXIS *)
        Kolben_LBK : BOOL := 0;
        (* BOOL Kolben_LBK *)
        Kolben_LFR : BOOL := 0;
        (* BOOL Kolben_LFR *)
        Kolben_Kolben_KinActual_Val : REAL := 0.0;
        (* REAL Kolben_Kolben_KinActual_Val *)
        Lichttsaster_IR : BOOL := 0;
        (* BOOL Lichttsaster_IR *)

	END_STRUCT;

ComTCP20_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 10;

        Kolben_MasterMaxSpeed : REAL := 0.0;
        (* REAL Kolben_MasterMaxSpeed *)
        Kolben_MasterForward : BOOL := 0;
        (* BOOL Kolben_MasterForward *)
        Kolben_MasterBack : BOOL := 0;
        (* BOOL Kolben_MasterBack *)
        Kolben_MasterInhibit : BOOL := 0;
        (* BOOL Kolben_MasterInhibit *)
        Kolben_MasterPos : REAL := 0.0;
        (* REAL Kolben_MasterPos *)
        Kolben_Override : REAL := 0.0;
        (* REAL Kolben_Override *)
        Kolben_MAX_SPD : REAL := 0.0;
        (* REAL Kolben_MAX_SPD *)
        Kolben_FWD : BOOL := 0;
        (* BOOL Kolben_FWD *)
        Kolben_KinInhibit : BOOL := 0;
        (* BOOL Kolben_KinInhibit *)
        Kolben_BWD : BOOL := 0;
        (* BOOL Kolben_BWD *)

	END_STRUCT;


END_TYPE
