(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: iPhysics_2.4.master                                          *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.12436.master                                             *)
(*        Build: e734d0bb0                                                    *)
(*         Date: 2021-11-11, Time: 14:50:37                                   *)
(*                                                                            *)

TYPE
ComTCP_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 10;

        Kolben_Magazin_LBK : BOOL := 0;
        (* BOOL Kolben_Magazin_LBK *)
        Kolben_Magazin_LFR : BOOL := 0;
        (* BOOL Kolben_Magazin_LFR *)
        Kolben_Ausschub_LBK : BOOL := 0;
        (* BOOL Kolben_Ausschub_LBK *)
        Kolben_Ausschub_LFR : BOOL := 0;
        (* BOOL Kolben_Ausschub_LFR *)
        Kolben_Hochfahren_LBK : BOOL := 0;
        (* BOOL Kolben_Hochfahren_LBK *)
        Kolben_Hochfahren_LFR : BOOL := 0;
        (* BOOL Kolben_Hochfahren_LFR *)
        Kolben_Presse_LBK : BOOL := 0;
        (* BOOL Kolben_Presse_LBK *)
        Kolben_Presse_LFR : BOOL := 0;
        (* BOOL Kolben_Presse_LFR *)
        Neue_Komponente2_IR : BOOL := 0;
        (* BOOL Neue_Komponente2_IR *)
        Neue_Komponente3_IR : BOOL := 0;
        (* BOOL Neue_Komponente3_IR *)

	END_STRUCT;

ComTCP_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 8;

        Kolben_Magazin_FWD : BOOL := 0;
        (* BOOL Kolben_Magazin_FWD *)
        Kolben_Magazin_BWD : BOOL := 0;
        (* BOOL Kolben_Magazin_BWD *)
        Kolben_Ausschub_FWD : BOOL := 0;
        (* BOOL Kolben_Ausschub_FWD *)
        Kolben_Ausschub_BWD : BOOL := 0;
        (* BOOL Kolben_Ausschub_BWD *)
        Kolben_Hochfahren_FWD : BOOL := 0;
        (* BOOL Kolben_Hochfahren_FWD *)
        Kolben_Hochfahren_BWD : BOOL := 0;
        (* BOOL Kolben_Hochfahren_BWD *)
        Kolben_Presse_FWD : BOOL := 0;
        (* BOOL Kolben_Presse_FWD *)
        Kolben_Presse_BWD : BOOL := 0;
        (* BOOL Kolben_Presse_BWD *)

	END_STRUCT;


END_TYPE
