(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: iPhysics_2.4.master                                          *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.12436.master                                             *)
(*        Build: e734d0bb0                                                    *)
(*         Date: 2021-11-02, Time: 17:25:32                                   *)
(*                                                                            *)

TYPE
	ComTCP_INPUTS_32BIT : 	STRUCT 
		NumSignals : INT := 10;
		Kolben_Magazin_LBK : BOOL := 0; (*Kolben Magazin eingefahren*)
		Kolben_Magazin_LFR : BOOL := 0; (*Kolben Magazin ausgefahren*)
		Kolben_Ausschub_LBK : BOOL := 0; (*Kolben Ausschub eingefahren*)
		Kolben_Ausschub_LFR : BOOL := 0; (*Kolben Ausschub ausgefahren*)
		Kolben_Hochfahren_LBK : BOOL := 0; (*Kolben Senke eingefahren*)
		Kolben_Hochfahren_LFR : BOOL := 0; (*Kolben Senke ausgefahren*)
		Kolben_Presse_LBK : BOOL := 0; (*Kolben Presse eingefahren*)
		Kolben_Presse_LFR : BOOL := 0; (*Kolben Presse ausgefahren*)
		Lichttaster_Austrag : BOOL := 0; (*Lichttaster am Austrag 1= Material ausgetragen*)
		Lichttaster_Magazin : BOOL := 0; (*Lichttaster am Magazin 1= Material vorhanden*)
	END_STRUCT;
	ComTCP_OUTPUTS_32BIT : 	STRUCT 
		NumSignals : INT := 8;
		Kolben_Magazin_FWD : BOOL := 0; (*Kolben Magazin ausfahren*)
		Kolben_Magazin_BWD : BOOL := 0; (*Kolben Magazin einfahren*)
		Kolben_Ausschub_FWD : BOOL := 0; (*Kolben Ausschub ausfahren*)
		Kolben_Ausschub_BWD : BOOL := 0; (*Kolben Ausschub einfahren*)
		Kolben_Hochfahren_FWD : BOOL := 0; (*Kolben Senke hochfahren*)
		Kolben_Hochfahren_BWD : BOOL := 0; (*Kolben Senke herrunetrfahren*)
		Kolben_Presse_FWD : BOOL := 0; (*Kolben Presse herrunterfahren*)
		Kolben_Presse_BWD : BOOL := 0; (*Kolben Presse hochfahren*)
	END_STRUCT;
END_TYPE
